#!/bin/sh


menu(){
    printf "01. Download song\n"
    printf "02. Download video\n"
    printf "03. Download wallpaper\n"
    printf "04. Play videos in mpv\n"
    printf "05. Play audio in mpv\n"
    printf "06. Save clipbaord image in ~/Photos/Screenshots/\n"
    printf "07. Start downloading torrent from magnet\n"
    printf "08. QR Code\n"
    printf "09. Add link/url to bookmarks\n"
    printf "10. Add citation bib\n"
    printf "11. Download paper sci-hub\n"
}

spell_failed(){
    notify-send "Failed to cast spell"
}

choice=$(menu | dmenu -p "What to do" -i -l 20 | cut -d. -f1)
cbtext=$(xclip -o -selection clipboard)

case $choice in
    01)
	cd ~/Music && notify-send "Downloading Song" && yt-dlp -x "$cbtext" && notify-send "Download complete" || spell_failed
	break
	;;
    02)
	cd ~/Videos/yt && notify-send "Downloading Video" && yt-dlp "$cbtext" && notify-send "Download complete" || spell_failed
	break
	;;
    03)
	    cd ~/Photos/Wallpapers/ && curl -sLO "$cbtext" && notify-send "Done!" && cd && prompt=$(echo -e "Yes\nNo" | dmenu -i -p "Set as wallpaper?") && if [ $prompt == "Yes" ]
    then
	    setbg $(ls -td $HOME/Photos/Wallpapers/* | head -n 1)
	    fi || spell_failed
	break
	;;
    04)
	mpv "$cbtext" || spell_failed
	break
	;;
    05)
	mpv "$cbtext" || spell_failed
	break
	;;
    06)
	file=$(date +"%Y_%m_%d_%I_%M_%p_%s")
	xclip -selection clipboard -t image/png -o > $HOME/Photos/Screenshots/$file.png ||
	    spell_failed
	break
	;;
    07)
	    transmission-remote -a "$(xclip -selection clipboard -o)"
	break
	;;
    08)
	    qrencode -s 6 -l H -o "/tmp/test.png" "$(xclip -selection clipboard -o)" && sxiv /tmp/test.png && shred -fuz /tmp/test.png
	break
	;;
    09)
	   echo "$cbtext" >> ~/Work/Notes/misc/bookmarks && notify-send "Done!" || spell_failed
	break
	;;
    10)
	echo -e '\n' >> $HOME/Work/Thesis/final/citations.bib && \
		xclip -o -sel c >> $HOME/Work/Thesis/final/citations.bib || spell_failed
	break
	;;
    11)
	    $HOME/.local/bin/paperdownloadscihub || spell_failed
	    break
	;;
esac
