#!/usr/bin/env bash

journal_paper=$(xclip -o | sed '/\n/d')

cd /tmp && rm -rf *.pdf

python $HOME/Work/Scripts/scihub.py -d $journal_paper &>/dev/null;

count=$(ls -1 *.pdf 2>/dev/null | wc -l)
if [[ $count -eq 1 ]]; then
	zathura *.pdf
	declare -a choice=("yes"
			   "no")
	decision=$(echo ${choice[@]} | sed 's/ /\n/g' | dmenu -i -p "Keep paper?")
	if [ "$decision" == "Yes" ];then
		mv *.pdf $HOME/Work/Papers/PIV
		notify-send "Paper saved to \"Papers\" directory"
		else
			rm -rf *.pdf
			notify-send "Paper deleted"
	fi
	else
		notify-send -u critical -t 3000 "Paper not found 😭" && exit
fi
