#!/usr/bin/env bash

dependency_check ()
{
	[[ -z $(which dmenu) || -z $(which notify-send) || -z $(which mpv) ]] >/dev/null 2>&1 &&
		echo "Make sure dmenu, libnotify and mpv are installed" && exit;
}

pause ()
{
	pkill -u $USER -i mpv >/dev/null 2>&1
}

random_play ()
{
	pkill -u $USER -i mpv
	rand=$(( $RANDOM % 5 ))
	mpv --no-video ${URLS[$rand]} >/dev/null 2>&1

}

dependecy_check;

declare -a Music=(Lofi Piano Jazz Rain Cafe Nature Random Stop)

declare -a URLS=(
		"http://0x0.st/NUzK"  # Lofi
		"http://0x0.st/NUzP"  # Piano
		"http://0x0.st/NUzZ"  # Jazz
		"http://0x0.st/NUzN"  # Rain
		"http://0x0.st/NUzq"  # Cafe
		"http://0x0.st/NUz0"  # Nature
		)

selection=$(printf "%s\n" ${Music[@]} | dmenu -i -p "What to play? ") && pause

case $selection in
	Lofi) mpv --no-video ${URLS[0]} >/dev/null 2>&1 ;;
	Piano) mpv --no-video ${URLS[1]} >/dev/null 2>&1 ;;
	Jazz) mpv --no-video ${URLS[2]} >/dev/null 2>&1 ;;
	Rain) mpv --no-video ${URLS[3]} >/dev/null 2>&1 ;;
	Cafe) mpv --no-video ${URLS[4]} >/dev/null 2>&1 ;;
	Nature) mpv --no-video ${URLS[5]} >/dev/null 2>&1 ;;
	Random) random_play ;;
	Stop) pause && exit ;;
	*) notify-send "Nothing played" && exit ;;
esac
