#!/usr/bin/env bash


curl -s "https://www.thesaurus.com/browse/$1" | html2text > /tmp/html_synonym

synonyms=$(sed -n '/other words for* /,/\*\*Meet/p' /tmp/html_synonym | grep '\* \[' | sed 's/\[/,/g;s/\]/,/g' | awk 'BEGIN {FS=","; print "Synonyms:\n-----------";i=1} {print i" - " $2;i+=1}')

printf "$synonyms\n" | head -n 17
