#!/usr/bin/env bash

tasks_db="$HOME/Work/tasks.md"

[[ -f "$tasks_db" ]] || touch $tasks_db

rm -rf /tmp/task_buffer &>/dev/null

mark_done ()
{
	# Deleting task from file
	chosen_task=$(sed "s/\[//g;s/\]//g" <<< $chosen_task)
	linenum=$(fgrep -n "$chosen_task" $tasks_db | cut -d: -f1)
	sed -i "$linenum d" $tasks_db
	# Marking it as done
	echo -e "- [X] $chosen_task ~~$(date)~~" | sed "s/ STARTED//g" >> $tasks_db
}

mark_started ()
{
	# Deleting task from file
	linenum=$(fgrep -n "$chosen_task" $tasks_db | cut -d: -f1)
	sed -i "$linenum d" $tasks_db
	# Marking it as started
	echo -e "- [o] $chosen_task STARTED" >> $tasks_db
}

create_task ()
{
	new_task=$(echo "" | dmenu -p "New task: ")
	[[ ! -z "$new_task" ]] && echo -e "- [ ] $new_task" >> $tasks_db || exit
}

edit_task ()
{

	if [[ "$chosen_task" == *STARTED* ]]; then
		 older_task=$(sed "s/ \[STARTED\]//g;s/[ \t]*$//g" <<< "$chosen_task")
		 echo "$older_task" > /tmp/task_buffer && st -e nvim /tmp/task_buffer
		 edited_task=$(cat /tmp/task_buffer)
		 if [[ "$older_task" == "$edited_task" ]]; then
			 exit
		 else
		 	sed -i "/$older_task/d" $tasks_db && echo -e "- [o] $edited_task STARTED" >> $tasks_db
		 fi
	else
		older_task="$chosen_task"
		echo -e "$older_task" > /tmp/task_buffer && st -e nvim /tmp/task_buffer
		edited_task=$(cat /tmp/task_buffer)
		if [[ "$older_task" == "$edited_task" ]]; then
		        exit
		else
			sed -i "/$older_task/d" $tasks_db && echo -e "- [ ] $edited_task" >> $tasks_db
		fi
	fi

}

recent_tasks=$(tac $tasks_db | sed -n '1,/^$/p' | sed '/^*$/d' | awk '/- \[ \]/;/- \[o\]/' | sed 's/- \[ \]//g' | sed 's/- \[o\]//g' | sed 's/^[ \t]*//g' | sed 's/[ \t]*$//g' | sed 's/STARTED/\[STARTED\]/g')

declare -a choices=("Create Task" "Mark Done" "Mark Started" "Edit Task" "New Entry")

printf -v singular_choice '%s\n' "${choices[@]}"

selected_choice=$(dmenu -i -p "Choose an option: " <<< "$singular_choice")

case $selected_choice in
	("Create Task") create_task ;;
	("Mark Done") chosen_task=$(echo "${recent_tasks[@]}" | sed 's/,/\n/g'|  dmenu -i -p "Mark done? " -l 20)
		[[ -z "$chosen_task" ]] && exit || mark_done ;;
	("Mark Started") chosen_task=$(echo "${recent_tasks[@]}" | sed "s/,/\n/g" | sed -r "/STARTED/d" |  dmenu -i -p "Mark started? " -l 20)
		[[ -z "$chosen_task" ]] && exit || mark_started ;;
	("Edit Task") chosen_task=$(echo "${recent_tasks[@]}" | sed 's/,/\n/g'|  dmenu -i -p "Edit task? " -l 20)
	[[ -z "$chosen_task" ]] && exit || edit_task ;;
	("New Entry") [[ ! -s "$tasks_db" ]] && echo -e "# $(date)\n" >> $tasks_db && create_task ||
		echo -e "\n# $(date)\n" >> $tasks_db && create_task
			break;;
	(*) break ;;
esac
